[project]
name = "1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.11.0",
    "numpy>=2.3.5",
    "pylint>=4.0.4",
    "pytest>=9.0.1",
]
